# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Live Or Die
subtitle: 
description: Take A Leap of Faith
keywords:
author: Akisaya
language:
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://akisaya.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:AkisAya/akisaya.github.io.git
  branch: master


theme_config:
  menu:
    home: / || home
    #about: /about/ || user
    tags: /tags/ || tags
    categories: /categories/ || th
    archives: /archives/ || archive
    #schedule: /schedule/ || calendar
    #sitemap: /sitemap.xml || sitemap
    #commonweal: /404/ || heartbeat

  # Enable/Disable menu icons / item badges.
  menu_settings:
    icons: true
    badges: false

  scheme: Pisces

  social:
    GitHub: https://github.com/akisaya || github
    E-Mail: mailto:akisaya@foxmail.com || envelope


  # Sidebar Avatar
  avatar:
    url: /uploads/avatar.jpg
    # If true, the avatar would be dispalyed in circle.
    rounded: true
    # The value of opacity should be choose from 0 to 1 to set the opacity of the avatar.
    opacity: 1
    # If true, the avatar would be rotated with the cursor.
    rotated: false

  sidebar:
    # Sidebar Position, available value: left | right (only for Pisces | Gemini).
    position: left
    display: post
    b2t: true

  codeblock:
    # Manual define the border radius in codeblock
    # Leave it empty for the default 1
    border_radius: 6
    # Add copy button on codeblock
    copy_button:
      enable: true
      # Show text copy result
      show_result: true

  scroll_to_more: false

  # Code Highlight theme
  # Available values: normal | night | night eighties | night blue | night bright
  # https://github.com/chriskempson/tomorrow-theme
  highlight_theme: normal

  # Enable "cheers" for archive page.
  cheers_enabled: true


  # ---------------------------------------------------------------
  # Third Party Services Settings
  # ---------------------------------------------------------------

  # Math Equations Render Support
  math:
    enable: false
    # Default(true) will load mathjax/katex script on demand
    # That is it only render those page who has 'mathjax: true' in Front Matter.
    # If you set it to false, it will load mathjax/katex srcipt EVERY PAGE.
    per_page: true
    engine: mathjax

  # Baidu Analytics ID
  #baidu_analytics:

  # Disqus
  disqus:
    enable: true
    shortname: akisaya
    count: true
    lazyload: false

  # Show Views/Visitors of the website/page with busuanzi.
  # Get more information on http://ibruce.info/2015/04/04/busuanzi/
  busuanzi_count:
    enable: true
    total_visitors: true
    total_visitors_icon: user
    total_views: true
    total_views_icon: eye
    post_views: true
    post_views_icon: eye

  # Enable baidu push so that the blog will push the url to baidu automatically which is very helpful for SEO
  baidu_push: true

  # Use velocity to animate everything.
  motion:
    enable: false